# bitcoinlib/transactions.pyi

from typing import Any

class Transaction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_input(self, *args: Any, **kwargs: Any) -> None: ...
    def add_output(self, *args: Any, **kwargs: Any) -> None: ...
    def sign(self, *args: Any, **kwargs: Any) -> None: ...
    def as_dict(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def raw_hex(self, *args: Any, **kwargs: Any) -> str: ...
    def verify(self, *args: Any, **kwargs: Any) -> bool: ...

class Key:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def public_hex(self, *args: Any, **kwargs: Any) -> str: ...
    @property
    def private_byte(self, *args: Any, **kwargs: Any) -> bytes: ...
